### ISSUE TITLE
您好 我对这个项目很感兴趣，请问已经开源的是完整源码吗

### ISSUE THREAD

**Issue by Ray-zyy** [PolarPeak/NIDS#1]

**Comment by PolarPeak** [comment]
项目目前是完整的，但支持检测的协议较少。当时只是为了毕设做的一个demo性质的东西

> _No description provided._

**Comment by Ray-zyy** [comment]
这个也是属于分布式系统叭？

**Comment by PolarPeak** [comment]
> 这个也是属于分布式系统叭？

不算吧，高并发场景估计很悬

**Comment by PolarPeak** [comment]
> 这个也是属于分布式系统叭？

你可以搞个ES集群。
